const easy = 'easy';
const medium = 'medium';
const hard = 'hard';

const data = [
  {
    well: 356,
    difficulty: easy,
    expectedProduction: 150,
    left: '40px',
    top: '40px',
  },
  {
    well: 357,
    difficulty: easy,
    expectedProduction: 200,
    left: '135px',
    top: '40px',
  },
  {
    well: 358,
    difficulty: medium,
    expectedProduction: 110,
    left: '230px',
    top: '40px',
  },
  {
    well: 359,
    difficulty: easy,
    expectedProduction: 130,
    left: '325px',
    top: '40px',
  },
  {
    well: 27,
    difficulty: hard,
    expectedProduction: 140,
    left: '420px',
    top: '40px',
  },
  {
    well: 25,
    difficulty: easy,
    expectedProduction: 50,
    left: '515px',
    top: '40px',
  },
  {
    well: 361,
    difficulty: easy,
    expectedProduction: 10,
    left: '610px',
    top: '40px',
  },
  {
    well: 32,
    difficulty: easy,
    expectedProduction: 110,
    left: '705px',
    top: '40px',
  },
  {
    well: 36,
    difficulty: medium,
    expectedProduction: 145,
    left: '800px',
    top: '40px',
  },
  {
    well: 362,
    difficulty: easy,
    expectedProduction: 200,
    left: '895px',
    top: '40px',
  },
  {
    well: 327,
    difficulty: hard,
    expectedProduction: 155,
    left: '40px',
    top: '140px',
  },
  {
    well: 322,
    difficulty: hard,
    expectedProduction: 60,
    left: '135px',
    top: '140px',
  },
  {
    well: 321,
    difficulty: hard,
    expectedProduction: 350,
    left: '230px',
    top: '140px',
  },
  {
    well: 319,
    difficulty: easy,
    expectedProduction: 80,
    left: '325px',
    top: '140px',
  },
  {
    well: 318,
    difficulty: easy,
    expectedProduction: 90,
    left: '420px',
    top: '140px',
  },
  {
    well: 349,
    difficulty: hard,
    expectedProduction: 120,
    left: '515px',
    top: '140px',
  },
  {
    well: 328,
    difficulty: easy,
    expectedProduction: 100,
    left: '610px',
    top: '140px',
  },
  {
    well: 325,
    difficulty: medium,
    expectedProduction: 60,
    left: '705px',
    top: '140px',
  },
  {
    well: 326,
    difficulty: easy,
    expectedProduction: 150,
    left: '800px',
    top: '140px',
  },
  {
    well: 320,
    difficulty: easy,
    expectedProduction: 150,
    left: '895px',
    top: '140px',
  },
  {
    well: 38,
    difficulty: easy,
    expectedProduction: 150,
    left: '5px',
    top: '200px',
  },
  {
    well: 329,
    difficulty: easy,
    expectedProduction: 150,
    left: '40px',
    top: '260px',
  },
  {
    well: 323,
    difficulty: easy,
    expectedProduction: 150,
    left: '135px',
    top: '260px',
  },
  {
    well: 317,
    difficulty: easy,
    expectedProduction: 150,
    left: '230px',
    top: '260px',
  },
  {
    well: 324,
    difficulty: medium,
    expectedProduction: 150,
    left: '325px',
    top: '260px',
  },
  {
    well: 316,
    difficulty: easy,
    expectedProduction: 150,
    left: '420px',
    top: '260px',
  },
  {
    well: 348,
    difficulty: hard,
    expectedProduction: 150,
    left: '515px',
    top: '260px',
  },
  {
    well: 338,
    difficulty: easy,
    expectedProduction: 150,
    left: '610px',
    top: '260px',
  },
  {
    well: 342,
    difficulty: easy,
    expectedProduction: 150,
    left: '705px',
    top: '260px',
  },
  {
    well: 339,
    difficulty: medium,
    expectedProduction: 150,
    left: '800px',
    top: '260px',
  },
  {
    well: 29,
    difficulty: easy,
    expectedProduction: 150,
    left: '895px',
    top: '260px',
  },
  {
    well: 360,
    difficulty: easy,
    expectedProduction: 150,
    left: '930px',
    top: '200px',
  },
];

export default data;
